version: '3.4'

volumes:
  wp_files:
    driver: local
    driver_opts: #options:
      device: /home/alazzari/data/wp_files #devices path (example, we have to create manually in the vm)
      o: bind #enables a specific host path to be linked to the container volume path
      type: none #empty volume that has no initial content.
  
  wp_db:
    driver: local
    driver_opts:
      device: /home/alazzari/data/wp_db
      o: bind
      type: none

networks:
  inception:
    name: inception_nw

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    networks:
      - inception
    volumes:
      - wp_files:/var/www/html
    ports: 
      - "443:443"
    depends_on:
      - wordpress
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    networks:
      - inception
    volumes:
      - wp_db:/var/lib/mysql
    restart: always
    ports: 
      - "3306:3306"
    environment:
      WP_DB_NAME:        ${WP_DB_NAME}
      WP_DB_USER:        ${WP_DB_USER}
      WP_DB_PASSWORD:    ${WP_DB_PASSWORD}
      DOMAIN_NAME:       ${DOMAIN_NAME}
      WP_ADMIN_USER:     ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL:    ${WP_ADMIN_EMAIL}
      WP_USER:           ${WP_USER}
      WP_PASSWORD:       ${WP_PASSWORD}
      WP_EMAIL:          ${WP_EMAIL}

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wp_files:/var/www/html
    restart: always
    ports: 
      - "9000:9000"
    environment:
      WP_DB_NAME:        ${WP_DB_NAME}
      WP_DB_USER:        ${WP_DB_USER}
      WP_DB_PASSWORD:    ${WP_DB_PASSWORD}
      DOMAIN_NAME:       ${DOMAIN_NAME}
      WP_ADMIN_USER:     ${WP_ADMIN_USER}
      WP_ADMIN_PASSWORD: ${WP_ADMIN_PASSWORD}
      WP_ADMIN_EMAIL:    ${WP_ADMIN_EMAIL}
      WP_USER:           ${WP_USER}
      WP_PASSWORD:       ${WP_PASSWORD}
      WP_EMAIL:          ${WP_EMAIL}