version: '3.4'

volumes:
  wp_files:
    driver: local
    driver_opts: #options:
      device: /home/${USER}/data/wp_files #devices path (example, we have to create manually in the vm)
      o: bind #enables a specific host path to be linked to the container volume path
      type: none #empty volume that has no initial content.
  
  wp_db:
    driver: local
    driver_opts:
      device: /home/${USER}/data/wp_db
      o: bind
      type: none

networks:
  inception:
    name: inception_nw

services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/
    image: nginx
    networks:
      - inception
    volumes:
      - wp_files:/var/www/html
    ports: 
      - "443:443"
    depends_on:
      - wordpress
    restart: always

  mariadb:
    build: ./requirements/mariadb/
    container_name: mariadb
    networks:
      - inception
    volumes:
      - wp_db:/var/lib/mysql
    restart: always
    ports: 
      - "3306:3306"
    environment:
      USER_42: ${USER_42}
      DOMAIN_NAME: ${DOMAIN_NAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DB_ROOT_PWD: ${DB_ROOT_PWD}
      DATABASE_ADMIN: ${DATABASE_ADMIN}
      DATABASE_ADMIN_PWD: ${DATABASE_ADMIN_PWD}

  wordpress:
    build: ./requirements/wordpress/
    container_name: wordpress
    networks:
      - inception
    volumes:
      - wp_files:/var/www/html
    restart: always
    ports: 
      - "9000:9000"
    environment:
      USER_42: ${USER_42}
      DOMAIN_NAME: ${DOMAIN_NAME}
      DATABASE_NAME: ${DATABASE_NAME}
      DB_ROOT_PWD: ${DB_ROOT_PWD}
      DATABASE_ADMIN: ${DATABASE_ADMIN}
      DATABASE_ADMIN_PWD: ${DATABASE_ADMIN_PWD}
      WP_ADMIN_EMAIL: ${WP_ADMIN_EMAIL}