version: '3.4'

services:
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
    networks:
      - inception
    ports:
      - "443:443"
  
  mariadb:
    container_name: mariadb
    build:

  wordpress:
    container_name: wordpress
    build:


