version: '3.4'

services:
  nginx:
    container_name: nginx
    build: ./nginx

  mariadb:
    container_name: mariadb
    build:

  wordpress:
    container_name: wordpress
    build:


